#pragma once
#pragma once
// C
#include <conio.h>
#include <intrin.h>
#include <stdio.h>
#include <tchar.h>
#include <stdlib.h>
#include <malloc.h>
#include <memory.h>
#include <tchar.h>
// C++
#include <ios>
#include <format>
#include <stdexcept>
#include <exception>
#include <array>
#include <mutex>
#include <condition_variable>
#include <functional>
#include <memory>
#include <fstream>
#include <iostream>
#include <cstdint>
#include <cassert>
#include <cstdlib>
#include <cwchar>
#include <cstddef>
#include <atomic>
#include <thread>
#include <new>
#include <sstream>
#include <list>
#include <forward_list>
#include <vector>
#include <string>
#include <string_view>
#include <algorithm>
#include <initializer_list>
#include <unordered_map>
#include <ctime>
#include <map>
#include <variant>
#include <optional>
#include <filesystem>